config/routes.rb
Rails.application.routes.draw do
  resources :posts
  resources :pedidos
  root 'pedidos#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/itens_pedidos.rb
class ItensPedidos < ApplicationRecord
  belongs_to :pedido
end

app/models/pedido.rb
class Pedido < ApplicationRecord
    has_many :itens_pedidos, dependent: :destroy
    accepts_nested_attributes_for :itens_pedidos, allow_destroy: true
  end
  

app/models/post.rb
class Post < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pedidos_controller.rb
class PedidosController < ApplicationController
    before_action :set_pedido, only: %i[show edit update destroy]
  
    def index
      @pedidos = Pedido.all
    end
  
    def show
    end
  
    def new
      @pedido = Pedido.new
      @pedido.itens_pedidos.build
    end
  
    def edit
    end
  
    def create
      @pedido = Pedido.new(pedido_params)
  
      if @pedido.save
        redirect_to @pedido, notice: 'Pedido criado com sucesso.'
      else
        render :new
      end
    end
  
    def update
      if @pedido.update(pedido_params)
        redirect_to @pedido, notice: 'Pedido atualizado com sucesso.'
      else
        render :edit
      end
    end
  
    def destroy
      @pedido.destroy
      redirect_to pedidos_url, notice: 'Pedido excluído com sucesso.'
    end
  
    private
  
    def set_pedido
      @pedido = Pedido.find(params[:id])
    end
  
    def pedido_params
      params.require(:pedido).permit(:data_hora, :numero_nota_fiscal, :valor_frete, :valor_desconto, :valor_total, itens_pedido_attributes: [:id, :nome, :quantidade, :preco, :_destroy])
    end
  end
  

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pedidos_helper.rb
module PedidosHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PedidoApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pedidos/edit.html.erb
<h1><%= action_name.capitalize %> Pedido</h1>

<%= form_with(model: @pedido, local: true) do |form| %>
  <% if @pedido.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pedido.errors.count, "error") %> proíbem este pedido de ser salvo:</h2>

      <ul>
        <% @pedido.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :data_hora %>
    <%= form.datetime_select :data_hora %>
  </div>

  <div class="field">
    <%= form.label :numero_nota_fiscal %>
    <%= form.text_field :numero_nota_fiscal %>
  </div>

  <div class="field">
    <%= form.label :valor_frete %>
    <%= form.number_field :valor_frete, step: 0.01 %>
  </div>

  <div class="field">
    <%= form.label :valor_desconto %>
    <%= form.number_field :valor_desconto, step: 0.01 %>
  </div>

  <div class="field">
    <%= form.label :valor_total %>
    <%= form.number_field :valor_total, step: 0.01 %>
  </div>

  <h3>Itens do Pedido</h3>
  <%= form.fields_for :itens_pedido do |item_form| %>
    <div class="field">
      <%= item_form.label :nome %>
      <%= item_form.text_field :nome %>
    </div>

    <div class="field">
      <%= item_form.label :quantidade %>
      <%= item_form.number_field :quantidade %>
    </div>

    <div class="field">
      <%= item_form.label :preco %>
      <%= item_form.number_field :preco, step: 0.01 %>
    </div>

    <%= item_form.hidden_field :_destroy %>
    <%= link_to 'Remover', '#', class: 'remove_fields' %>
  <% end %>

  <%= link_to_add_fields "Adicionar Item", f, :itens_pedido %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<%= link_to 'Voltar', pedidos_path %>

app/views/pedidos/index.html.erb
<h1>Pedidos</h1>

<table>
  <thead>
    <tr>
      <th>Data e Hora</th>
      <th>Numero da Nota Fiscal</th>
      <th>Valor do Frete</th>
      <th>Valor do Desconto</th>
      <th>Valor Total</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pedidos.each do |pedido| %>
      <tr>
        <td><%= pedido.data_hora %></td>
        <td><%= pedido.numero_nota_fiscal %></td>
        <td><%= pedido.valor_frete %></td>
        <td><%= pedido.valor_desconto %></td>
        <td><%= pedido.valor_total %></td>
        <td><%= link_to 'Mostrar', pedido %></td>
        <td><%= link_to 'Editar', edit_pedido_path(pedido) %></td>
        <td><%= link_to 'Excluir', pedido, method: :delete, data: { confirm: 'Tem certeza?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Novo Pedido', new_pedido_path %>

app/views/pedidos/new.html.erb
<h1><%= action_name.capitalize %> Pedido</h1>

<%= form_with(model: @pedido, local: true) do |form| %>
  <% if @pedido.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pedido.errors.count, "error") %> proíbem este pedido de ser salvo:</h2>

      <ul>
        <% @pedido.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :data_hora %>
    <%= form.datetime_select :data_hora %>
  </div>

  <div class="field">
    <%= form.label :numero_nota_fiscal %>
    <%= form.text_field :numero_nota_fiscal %>
  </div>

  <div class="field">
    <%= form.label :valor_frete %>
    <%= form.number_field :valor_frete, step: 0.01 %>
  </div>

  <div class="field">
    <%= form.label :valor_desconto %>
    <%= form.number_field :valor_desconto, step: 0.01 %>
  </div>

  <div class="field">
    <%= form.label :valor_total %>
    <%= form.number_field :valor_total, step: 0.01 %>
  </div>

  <h3>Itens do Pedido</h3>
  <%= form.fields_for :itens_pedido do |item_form| %>
    <div class="field">
      <%= item_form.label :nome %>
      <%= item_form.text_field :nome %>
    </div>

    <div class="field">
      <%= item_form.label :quantidade %>
      <%= item_form.number_field :quantidade %>
    </div>

    <div class="field">
      <%= item_form.label :preco %>
      <%= item_form.number_field :preco, step: 0.01 %>
    </div>

    <%= item_form.hidden_field :_destroy %>
    <%= link_to 'Remover', '#', class: 'remove_fields' %>
  <% end %>

  <%= link_to_add_fields "Adicionar Item", f, :itens_pedido %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<%= link_to 'Voltar', pedidos_path %>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.content %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @post.content %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>